version: '2'
services:
  # mysql
  db01:
    restart: always
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
     - ../data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  # web
  web01:
    build: ./apache
    image: web:24
    privileged: true
    cap_add:
      - SYS_ADMIN
    ports:
      - "8082:80"
    links:
      - "db01:db01"
    volumes:
      - ../www:/var/www/html
      - ../logs:/var/log/httpd
      #- ../files/apache_conf/00_virtualhost.conf:/etc/httpd/conf.d/00_virtualhost.conf